environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
  - TARGET: i686-pc-windows-gnu
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-stable-${env:TARGET}.exe"
  - rust-stable-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test --verbose --all-features
